In [1]:
import numpy as np

arr = np.random.randint(1, 51, size=(5, 4))
print("Array:\n", arr)

anti_diag = [arr[i][-(i+1)] for i in range(min(arr.shape))]
print("Anti-diagonal:", anti_diag)

row_max = np.max(arr, axis=1)
print("Row-wise max:", row_max)

mean_val = np.mean(arr)
filtered_arr = arr[arr <= mean_val]
print("Elements <= mean:", filtered_arr)

def numpy_boundary_traversal(matrix):
    top = matrix[0, :]
    right = matrix[1:-1, -1]
    bottom = matrix[-1, ::-1]
    left = matrix[-2:0:-1, 0]
    return np.concatenate([top, right, bottom, left]).tolist()

print("Boundary traversal:", numpy_boundary_traversal(arr))


Array:
 [[17 29 19 41]
 [10 44 16 31]
 [13 39 34 44]
 [10 31 19 21]
 [42 41 31  2]]
Anti-diagonal: [np.int64(41), np.int64(16), np.int64(39), np.int64(10)]
Row-wise max: [41 44 44 31 42]
Elements <= mean: [17 19 10 16 13 10 19 21  2]
Boundary traversal: [17, 29, 19, 41, 31, 44, 21, 2, 31, 41, 42, 10, 13, 10]
